### ISSUE TITLE
Faille de sécurité

### ISSUE THREAD

**Issue by LaDetox87** [enzolhtt/Blog#1]
La route ip/admin est accessible pour tous les utilisateurs même ceux qui ne sont pas admin! Il faudrait que dans ton controller tu vérifies le rôle de l'utilisateur connecté pour vérifier s'il peut accéder au ip/admin , sinon lui présenter un message expliquant la situation.

**Comment by enzolhtt** [comment]
Bonjour à toi LaDetox87,
J'ai pris compte de ton message et je viens à l'instant de faire une vérification du rôle de l'utilisateur avant de pouvoir accéder à certaines routes.
Bonne journée.
